.PHONY: clean All

All:
	@echo "----------Building project:[ preproc - Debug ]----------"
	@cd "preproc" && "$(MAKE)" -f  "preproc.mk"
clean:
	@echo "----------Cleaning project:[ preproc - Debug ]----------"
	@cd "preproc" && "$(MAKE)" -f  "preproc.mk" clean
