.PHONY: clean All

All:
	@echo "----------Building project:[ float - Debug ]----------"
	@cd "float" && "$(MAKE)" -f  "float.mk"
clean:
	@echo "----------Cleaning project:[ float - Debug ]----------"
	@cd "float" && "$(MAKE)" -f  "float.mk" clean
