.PHONY: clean All

All:
	@echo "----------Building project:[ boolean - Debug ]----------"
	@cd "boolean" && "$(MAKE)" -f  "boolean.mk"
clean:
	@echo "----------Cleaning project:[ boolean - Debug ]----------"
	@cd "boolean" && "$(MAKE)" -f  "boolean.mk" clean
