.PHONY: clean All

All:
	@echo "----------Building project:[ quith - Debug ]----------"
	@cd "quith" && "$(MAKE)" -f  "quith.mk"
clean:
	@echo "----------Cleaning project:[ quith - Debug ]----------"
	@cd "quith" && "$(MAKE)" -f  "quith.mk" clean
