.PHONY: clean All

All:
	@echo "----------Building project:[ integers - Debug ]----------"
	@cd "integers" && "$(MAKE)" -f  "integers.mk"
clean:
	@echo "----------Cleaning project:[ integers - Debug ]----------"
	@cd "integers" && "$(MAKE)" -f  "integers.mk" clean
