.PHONY: clean All

All:
	@echo "----------Building project:[ varSize - Debug ]----------"
	@cd "varSize" && "$(MAKE)" -f  "varSize.mk"
clean:
	@echo "----------Cleaning project:[ varSize - Debug ]----------"
	@cd "varSize" && "$(MAKE)" -f  "varSize.mk" clean
