.PHONY: clean All

All:
	@echo "----------Building project:[ debugvar - Debug ]----------"
	@cd "debugvar" && "$(MAKE)" -f  "debugvar.mk"
clean:
	@echo "----------Cleaning project:[ debugvar - Debug ]----------"
	@cd "debugvar" && "$(MAKE)" -f  "debugvar.mk" clean
