.PHONY: clean All

All:
	@echo "----------Building project:[ paramfunct - Debug ]----------"
	@cd "paramfunct" && "$(MAKE)" -f  "paramfunct.mk"
clean:
	@echo "----------Cleaning project:[ paramfunct - Debug ]----------"
	@cd "paramfunct" && "$(MAKE)" -f  "paramfunct.mk" clean
