.PHONY: clean All

All:
	@echo "----------Building project:[ datatype - Debug ]----------"
	@cd "datatype" && "$(MAKE)" -f  "datatype.mk"
clean:
	@echo "----------Cleaning project:[ datatype - Debug ]----------"
	@cd "datatype" && "$(MAKE)" -f  "datatype.mk" clean
