.PHONY: clean All

All:
	@echo "----------Building project:[ frvrddec - Debug ]----------"
	@cd "frvrddec" && "$(MAKE)" -f  "frvrddec.mk"
clean:
	@echo "----------Cleaning project:[ frvrddec - Debug ]----------"
	@cd "frvrddec" && "$(MAKE)" -f  "frvrddec.mk" clean
