.PHONY: clean All

All:
	@echo "----------Building project:[ multi - Debug ]----------"
	@cd "multi" && "$(MAKE)" -f  "multi.mk"
clean:
	@echo "----------Cleaning project:[ multi - Debug ]----------"
	@cd "multi" && "$(MAKE)" -f  "multi.mk" clean
