.PHONY: clean All

All:
	@echo "----------Building project:[ int - Debug ]----------"
	@cd "int" && "$(MAKE)" -f  "int.mk"
clean:
	@echo "----------Cleaning project:[ int - Debug ]----------"
	@cd "int" && "$(MAKE)" -f  "int.mk" clean
