.PHONY: clean All

All:
	@echo "----------Building project:[ hello - Debug ]----------"
	@cd "hello" && "$(MAKE)" -f  "hello.mk"
clean:
	@echo "----------Cleaning project:[ hello - Debug ]----------"
	@cd "hello" && "$(MAKE)" -f  "hello.mk" clean
