.PHONY: clean All

All:
	@echo "----------Building project:[ program - Debug ]----------"
	@cd "program" && "$(MAKE)" -f  "program.mk"
clean:
	@echo "----------Cleaning project:[ program - Debug ]----------"
	@cd "program" && "$(MAKE)" -f  "program.mk" clean
