.PHONY: clean All

All:
	@echo "----------Building project:[ char - Debug ]----------"
	@cd "char" && "$(MAKE)" -f  "char.mk"
clean:
	@echo "----------Cleaning project:[ char - Debug ]----------"
	@cd "char" && "$(MAKE)" -f  "char.mk" clean
