.PHONY: clean All

All:
	@echo "----------Building project:[ debugger - Debug ]----------"
	@cd "debugger" && "$(MAKE)" -f  "debugger.mk"
clean:
	@echo "----------Cleaning project:[ debugger - Debug ]----------"
	@cd "debugger" && "$(MAKE)" -f  "debugger.mk" clean
