.PHONY: clean All

All:
	@echo "----------Building project:[ header - Debug ]----------"
	@cd "header" && "$(MAKE)" -f  "header.mk"
clean:
	@echo "----------Cleaning project:[ header - Debug ]----------"
	@cd "header" && "$(MAKE)" -f  "header.mk" clean
